### ISSUE TITLE
PHP requirements mismatch

### ISSUE THREAD

**Issue by maurotdo** [api-platform/api-platform#420] opened 2017-09-19 17:35 UTC
Hi,
api-platform/api-platform v2.1 requires PHP 7.0+, but depends on symfony/symfony 3.3.x which requires PHP 7.1

As a consequence v2.1 cannot be installed on a PHP 7.0 environment. Intended or bug ?

**Comment by dunglas** [comment] 2017-09-21 09:54
Closing as duplicate of #421. (the problem isn't Symfony, it must be investigated)

**Closed by dunglas** 2017-09-21 09:54 UTC
