### ISSUE TITLE
Upgrading from 2.1 to 2.3

### ISSUE THREAD

**Issue by mmplanet** [api-platform/api-platform#831] opened 2018-09-07 17:26 UTC
Hi, we are currently using API-Platform in production for a REST API. We are seeing slow Serialization as objects get bigger and we are thinking about upgrading to Symfony4 and API-Platform 2.3.

Is the upgrade necessarily to improve Serialization performance? We are already using APCU and Groups caching.

Is there a document with the migration steps between API-Platform under Symfony 3.4 and Symfony 4?

Thanks

**Comment by dunglas** [comment] 2018-09-07 18:13
Yes, there is a very impressive performance improvement in the latest version: https://dunglas.fr/2018/07/api-platform-2-3-major-perf-improvement-api-evolution-deprecation-better-dev-tools-and-much-more/

The upgrade should be smooth, you just have to upgrade `api-platform/core` to 2.3 and `symfony/serializer` to 4.1. All other Symfony components your project currently relies on can stick to 3.4.

You shouldn't have to change any code.

**Comment by mmplanet** [comment] 2018-09-07 19:49
Hi @dunglas, thank you.

The results are rather similar after doing the upgrade, if not slower than before. Anything I might be missing?

**Comment by dunglas** [comment] 2018-09-07 20:42
@mmplanet you're in prod mode? Can you share a Blackfire profile?

**Comment by mmplanet** [comment] 2018-09-09 14:11
@dunglas In prod mode, Blackfire not installed. I can go in dev mode and share the Symfony profiler data, but I guess that's not really relevant.

**Comment by dunglas** [comment] 2018-09-09 15:07
A profile on the prod server in prod env would be more accurate, but a profile in prod env on a dev machine should be enough. You should use a copy of the prod database in case the issue is related to SQL queries.

The only way to see what’s going on is to measure.

**Comment by mmplanet** [comment] 2018-09-09 15:43
@dunglas Thanks for the tips. We will install Blackfire as we wanted to do some performance assessment anyway. Meanwhile, the upgrade to API-Platform 2.3 broke a lot of our routes. We had some GET routes with custom Item Data Providers that allowed both IDs and slugs for {$id}. Those routes are no longer working with slugs as IntergerDenormalizer->denormalize() always returns 0 for the ones with them. Any way to add a StringDenormalizer or something like that?

**Comment by antograssiot** [comment] 2019-04-11 17:02
closing as I think everything has been answered here or followed in an other issue in core

**Closed by antograssiot** 2019-04-11 17:02 UTC
