### ISSUE TITLE
api-platform/api-platform doesn't work on PHP 7.0

### ISSUE THREAD

**Issue by maurotdo** [api-platform/api-platform#421] opened 2017-09-19 17:47 UTC
At this time it is not possible to install api-platform on PHP 7.0 via composer create-project:

 - v2.1 requires symfony 3.3 which requires php 7.1 (that may be intended, but composer.json is satisfied by php 7.0)

 - v2.0, which used to be compatible with php 7.0 is currently broken for 7.0 (it depends on api-platform/core ^2.0 - check the ^) which currently resolves to 2.1 and consequently requires symfony 3.3 components (requiring php 7.1), conflicting with the requirement for symfony 3.2 in the composer.json for v2.0

**Comment by maurotdo** [comment] 2017-09-19 17:53
The fix for v2.0 would be changing the requirement for
`"api-platform": "^2.0"` 
to
`"api-platform": "~2.0"` 

For v2.1 i don't know, is the software compatible with symfony 3.2 ?
If not, drop support for php 7.0 and change composer.json to require php 7.1+
If yes, change composer.json to lower the requirement on symfony/symfony to 3.2

**Comment by COil** [comment] 2017-09-21 09:33
Same problem, can't switch to 7.1 , it should support 7.0 IMHO.

**Comment by dunglas** [comment] 2017-09-21 09:52
Symfony 3.3 is compatbile with PHP 5.4+. The problem is elsewhere: https://github.com/symfony/symfony/blob/v3.3.0/composer.json

**Comment by dunglas** [comment] 2017-09-21 09:55
(And yes, we're still committed to support 7.0 for now)

**Comment by dunglas** [comment] 2017-09-21 09:56
Btw core 2.1 is definitely compatible with 7.0: https://travis-ci.org/api-platform/core (tests are green on 7.0).

The problem should be in the dependencies of the standard edition.

**Comment by COil** [comment] 2017-09-21 15:46
The core yes may be. But it as it includes the schema generator package which uses PHP 7.1 the composer update will fail.

**Comment by dunglas** [comment] 2017-09-21 18:44
Good catch I totally forgot about that. There is a quick fix: allow both schema-generator 1 and 2.

**Comment by dunglas** [comment] 2017-10-03 11:43
Fixed by #431.

**Closed by dunglas** 2017-10-03 11:43 UTC
Labels: Hacktoberfest
