### ISSUE TITLE
nginx: [emerg] host not found in upstream "cache-proxy" 

### ISSUE THREAD

**Issue by unlikenesses** [api-platform/api-platform#1135] opened 2019-05-10 12:52 UTC
After a fresh install, when I visit `https://localhost` I get an error "localhost refused to connect." Mac OS High Sierra / Docker 2.0.0.3

This is from version 2.4.2, installed by unpacking the `.tar.gz` file locally. I then run `docker-compose pull` and `docker-compose up -d`, which worked without errors. 

When I look in the logs, 2 things look suspicious:

1.  

> h2-proxy_1 | nginx: [emerg] host not found in upstream "cache-proxy" in /etc/nginx/conf.d/default.conf:58

2. 

> cache-proxy_1 | Error:
cache-proxy_1  | Message from VCC-compiler:
cache-proxy_1  | Expected return action name.
cache-proxy_1  | ('/usr/local/etc/varnish/default.vcl' Line 67 Pos 13)
cache-proxy_1  |     return (miss);

**Comment by deantomasevic** [comment] 2019-05-11 10:56
Hi @unlikenesses 

i had the same error.
Try this: https://github.com/api-platform/api-platform/issues/1109#issuecomment-485162978

Dean

**Comment by teohhanhui** [comment] 2019-05-11 11:02
Duplicate of #1109

**Closed by teohhanhui** 2019-05-11 11:02 UTC
