### ISSUE TITLE
Does the MIT license conflicts with React BSD + patents license?

### ISSUE THREAD

**Issue by mickaelandrieu** [api-platform/api-platform#406] opened 2017-09-04 18:08 UTC
Hello,

this question is worrying me since days and I can't find the answer: as Api platform depends on React and as React is not using a real "open source" [license](https://code.facebook.com/posts/112130496157735/explaining-react-s-license/), what are the risks to use Api Platform or any-dependent project using React?

I'm pretty sure the actual MIT license can't be applied because the Patents claimed by Facebook can't be canceled, to be more precise this part of MIT license can't be applied as it `to deal
in the Software without restriction`.

Should we notice the developer, the end users? Should we use the BSD + patents license like Facebook did?

Mickaël

**Comment by soyuka** [comment] 2017-09-04 18:13
👍 IMO the latest sentence is true, because react is licensed as BSD + patents we should follow the same rules. However, we could replace react with preact and keep everything MIT (it's plug&play).

**Comment by dunglas** [comment] 2017-09-04 18:46
React is a soft dependency of the framework. If you don't use it, you're definitely not affected by its licence. 3 components use it:

- The version of Swagger UI included in 2.1 (the one in 2.0 isn't affected). Maybe should we not ship this tool by default until the license problem is solved.
- The SPA generator. I don't think that this generator is affected because it doesn't ship react directly (we are in the process of adding support of other frameworks such as Angular in this tool).
- The admin component. For this one it's more complicated and honestly I don't know. We depend of Admin On Rest and AOR uses React.
Maybe @fzaninotto has a hint? But you can use API Platform without this component.

**Comment by dunglas** [comment] 2017-09-04 18:49
Regarding Preact, it it works and has a better license, we should definitely switch (and let the user switch back to React if he wants too).

**Comment by dunglas** [comment] 2017-09-04 19:25
Preact is not a solution. `preact-compat` depends of `facebook/prop-types` (`https://github.com/developit/preact-compat/blob/master/package.json#L87`). Prop-types has the same license than React.

**Comment by soyuka** [comment] 2017-09-04 20:40
Interesting! Anyway it seems like prop-types should be disabled in production, and therefore not included in the code according to the README? 

Also https://github.com/developit/preact-compat/issues/285

**Comment by mickaelandrieu** [comment] 2017-09-04 22:32
Note I don't say we/you? should remove React! As a developer really annoying with legal stuff I'm really worried about it. I've asked to my family lawyer but he was not able to answer me.

I don't want to fear anyone or whatever, the `preact` alternative looks good to me.

Thanks for your answers!

**Comment by developit** [comment] 2017-09-05 00:54
You can alias `proptypes/disabled` in for `prop-types`. It's just a bunch of empty functions.

**Comment by dunglas** [comment] 2017-09-05 08:06
Great :)

Swagger UI also use a bunch of other deps under the same license: https://github.com/swagger-api/swagger-ui/blob/master/package.json#L55-L58

Do you know if it's possible to replace them @developit?

**Comment by soyuka** [comment] 2017-09-05 08:15
Looks like `react-addons-test-utils` and `react-addons-perf` should be dev dependencies. `react-addons-shallow-compare` seems to be a simple non-recursive check and there is [a preact alternative here](https://github.com/tkh44/preact-shallow-compare/blob/master/src/index.js).

**Comment by fzaninotto** [comment] 2017-09-05 09:04
admin-on-rest's licence is MIT. We have a hard dependency on React, but we don't mind the BSD+Patents licence - we think it's fair.

IMHO, if you care about it, that means you think you can sue Facebook in the future, so you're very rich, and you shouldn't use open-source in that case : spend you money to help editors! ;)

**Comment by dunglas** [comment] 2017-09-05 09:53
@fzaninotto I agree with your last sentence, but it can be a barrier to adoption.

**Comment by mickaelandrieu** [comment] 2017-09-05 13:02
@fzaninotto the fact is that Patents conflicts with MIT license: MIT license means you can use a software without any restriction. This is not about what do you mind or not, this is about using the right license. As for now, and because admin on rest have an hard dependency on React, the project can't be licensed under MIT *because* it doesn't respect the MIT license...

**Comment by dunglas** [comment] 2017-09-05 13:12
@mickaelandrieu it's not true: Facebook made it clear that you can license your project under the MIT license event if it has a dependency against React:

> As has always been the case, source code licensed under the Facebook BSD + Patents license can be combined with source code licensed under other open source licenses like BSD, MIT, Apache 2.0, and GPL. Additionally, as has always been the case, you may distribute BSD + Patents licensed code with other popular open source licenses, such as BSD, MIT, Apache 2.0, and GPL. 

https://code.facebook.com/posts/112130496157735/explaining-react-s-license/

**Comment by mickaelandrieu** [comment] 2017-09-05 13:35
how is it possible ? MIT say "you can use the software without any restrictions" and a Patent is a restriction... you can't be compliant with MIT license, or I've misunderstood MIT license terms (which is possible :) )

**Comment by soyuka** [comment] 2017-09-05 14:04
@mickaelandrieu I think that the MIT licence applies to the current licensed project, not it's dependencies. Indeed, you don't have restrictions with the software, you can edit and redistribute. Usually when you do so, you don't do it on the dependencies, or you'd take a look at this dependency as a new project, and therefore read the dependency license.

**Comment by soyuka** [comment] 2017-09-11 07:17
> I’m going to lock this issue because bumping it is not very productive. We’ve made our position clear many times, and if you don’t plan to sue Facebook over patents, you have nothing to worry about. If you plan to engage in patent litigation then FB withdraws additional protections given by the grant (**which you don’t even have in the first place with open source libraries like MIT**). Yes, the grant conditions are broader than Apache, but so far it works well for many companies that choose not to sue each other over software patents. This is why we don’t intend to change the strategy in the near future.

https://github.com/facebook/react/issues/7293 

Closing this as resolved.

**Closed by soyuka** 2017-09-11 07:18 UTC

**Comment by mickaelandrieu** [comment] 2017-09-11 07:48
Thanks for your answers, after a lot of reading, I'm coming to the same conclusions.

When you sue Facebook for patents (lol?) you are losing the right to use patents provided with React but this doesn't affect the rights provided by the initial BSD-3 licence on React code. I'll write something about it: it's a fair situation.

Still, I'm wondering if we should add a note for people who own patents?

**Comment by soyuka** [comment] 2017-09-11 07:56
@mickaelandrieu hmm, we may but only on packages directly depending on `react`. For example, in the core we only use `react` because of `swagger`, therefore I'm not sure it's worth mentioning... Just disable swagger and there isn't any react anymore no?

**Comment by mickaelandrieu** [comment] 2017-09-11 08:03
@soyuka as you like, it's only a suggestion: I - also - consider this issue closed :)

Thank you for your time!

**Comment by dunglas** [comment] 2017-09-23 06:57
The issue is definitely gone: https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

**Comment by mickaelandrieu** [comment] 2017-09-23 11:27
yes! :)
