### ISSUE TITLE
PHP Fatal error:  Uncaught RuntimeException: APP_ENV

### ISSUE THREAD

**Issue by mozgbrasil** [api-platform/api-platform#868] opened 2018-10-17 20:27 UTC
Good Morning

See the error performing composer update

![captura de tela de 2018-10-17 17-25-54](https://user-images.githubusercontent.com/17202780/47114299-ced38800-d231-11e8-992b-331e17a87b74.png)

See that it was solved by running the command

  composer require --dev symfony/dotenv

**Comment by teohhanhui** [comment] 2018-11-14 14:29
Duplicate of #751

**Closed by teohhanhui** 2018-11-14 14:29 UTC
