### ISSUE TITLE
Making Vendor Entity Api-Platform Resource

### ISSUE THREAD

**Issue by vipulw2011** [api-platform/api-platform#1352] opened 2019-12-03 06:40 UTC
I am using DataDogAuditBundle for Audit Logs in my Symfony Application. I want to create 2 Entities of this bundle which are in vendor folder as APl-Platform resource. I have created a YAML file for it and also added path in mappings. Also tried clearing cache, but still it gives error saying "No Route Found". Is there something I am doing wrong ?

![image](https://user-images.githubusercontent.com/56351817/70026448-d8e75000-15c5-11ea-9ed5-df8b00c0ddf3.png)

![image](https://user-images.githubusercontent.com/56351817/70026481-eef51080-15c5-11ea-8438-a91a72af24fb.png)

**Comment by teohhanhui** [comment] 2019-12-04 11:26
Duplicate of #891

**Closed by teohhanhui** 2019-12-04 11:26 UTC
