### ISSUE TITLE
[QUESTION]: including nested relationships (location -> catalogRecords -> catalogItems)

### ISSUE THREAD

**Issue by worthwhileindustries** [api-platform/api-platform#1103] opened 2019-04-12 20:59 UTC
I get this error `App\Entity\Location - The referenced column name 'catalogID' has to be a primary key column on the target entity class 'App\Entity\CatalogItem'.`

However, the location api endpoint still works and the catalogItems get included. I'm not sure if this is an error that can be ignored? Anyone have any insight? 

locations have many catalogRecords and catalogRecords have many catalogItems 

`curl -X GET "http://localhost:8080/api/location?include=catalogItems,catalogRecords" -H "accept: application/vnd.api+json"`

I can't seem to do something like `include=catalogRecords.catalogItems,catalogRecords` to include the nested relationship

so, I created this relationship on the location entity.

```
// locationEntity
    /**
     * One catalogRecord has many catalogItems. This is the inverse side.
     * @ORM\ManyToMany(targetEntity="CatalogItem")
     * @ORM\JoinTable(name="catalog",
     *   joinColumns={
     *     @ORM\JoinColumn(name="locationID", referencedColumnName="locationID")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="catalogID", referencedColumnName="catalogID")
     *   }
     * )
     */
    private $catalogItems;
```

```
//location table
locationID

//catalogRecord table
catalogID
locationID

//catalogItem table
itemID
catalogID
```

**Comment by antograssiot** [comment] 2019-04-13 07:32
Nested inclusion is not supported yet. 
Any help would be welcome if you wish to controbute.
Closing as duplicate of #2365 and also related to #2675

**Closed by antograssiot** 2019-04-13 07:32 UTC
