### ISSUE TITLE
Using Symfony voters on collectionOperations (GET) 

### ISSUE THREAD

**Issue by AbbesBendaoud10** [api-platform/api-platform#1343] opened 2019-11-26 11:43 UTC
Hello everyone,

I want to use symfony voters in API PLATFROM, i don"t have any problem when i use it on itempsOperations (GET,PUT,DELETE) , but when i use it in collectionOperations especially in GET (POST works well) , i cannot acces to the $subject because in GET operation API PLATFORM returns an instance of "ApiPlatform\Core\Bridge\Doctrine\Orm\Paginator" and not entity object .

      * @ApiResource(
      *         collectionOperations={
      *              "GET"={
      *                   "access_control"="is_granted('GET', object)",
      *               },
      *               "POST"={
      *                   "access_control"="is_granted('ADD', object)",
      *                }
      *         }
      * )

Any proposal ?

**Comment by mahmoodbazdar** [comment] 2019-11-26 21:58
Hey
You can use DoctrineExtension and filter the results.
https://api-platform.com/docs/core/extensions/#custom-doctrine-orm-extension

**Comment by AbbesBendaoud10** [comment] 2019-11-27 15:32
@mahmoodbazdar  Thank you for your response, there is no possibility to work with voters ? 
Otherwise DQLEXTENSION is a nice alternative, but not the best one.

**Comment by AbbesBendaoud10** [comment] 2019-12-04 08:51
@soyuka  Any other solution ?

**Comment by dunglas** [comment] 2019-12-05 10:05
It's the intended behavior. You can call the methods of the `Paginator` instance if you want to access a specific item, or pass the paginator itself to your voter.
Anyway, it's always better to apply the filtering and security logic at the DBMS level. It allows to increase the security, to not create "holes" in pages (and then break pagination) and to not over-fetch unnecessary data.

**Comment by dunglas** [comment] 2019-12-05 10:05
Closing as I don't see what more we can do.

**Closed by dunglas** 2019-12-05 10:05 UTC

**Comment by AbbesBendaoud10** [comment] 2019-12-05 10:12
@dunglas  Thank you for your response , so do you think that the best idea is to use DoctrineExtension to manage permissions on Collections ?  as @mahmoodbazdar  said ?

**Comment by phil-schreiber** [comment] 2020-04-29 08:11
Hey, just stumbled upon this. What I noticed is that on POST operation the object will always be null. So the $subject param of the voter is always null and there is no way to apply the voter to the operation.

IMHO this breaks the whole implementation of custom voters.

**Comment by michael-schaefer-eu** [comment] 2020-05-04 06:44
Hi @phil-schreiber  that is because `security` is run before denormalization. That means at this time in a POST Request your data has not been denormalized into an object AND because you create one you don't have an object from store. So you have to use `security_post_denormalize` on Collection Post:

```php
/**
 * @ApiResource(
 *     iri="https://schema.org/Person",
 *     collectionOperations={
 *          "get",
 *          "post" = { "security_post_denormalize" = "is_granted('USER_CREATE', object)" }
 *     },
 *     itemOperations={
 *          "get" = { "security" = "is_granted('USER_READ', object)" },
 *          "put" = { "security" = "is_granted('USER_EDIT', object)" },
 *          "delete" = { "security" = "is_granted('USER_DELETE', object)" }
 *     },
 *     shortName="user",
 *  [...]
```

**Comment by phil-schreiber** [comment] 2020-05-04 08:21
> Hi @phil-schreiber that is because `security` is run before denormalization. That means at this time in a POST Request your data has not been denormalized into an object AND because you create one you don't have an object from store. So you have to use `security_post_denormalize` on Collection Post:
> 
> ```
> /**
>  * @ApiResource(
>  *     iri="https://schema.org/Person",
>  *     collectionOperations={
>  *          "get",
>  *          "post" = { "security_post_denormalize" = "is_granted('USER_CREATE', object)" }
>  *     },
>  *     itemOperations={
>  *          "get" = { "security" = "is_granted('USER_READ', object)" },
>  *          "put" = { "security" = "is_granted('USER_EDIT', object)" },
>  *          "delete" = { "security" = "is_granted('USER_DELETE', object)" }
>  *     },
>  *     shortName="user",
>  *  [...]
> ```

Thanks a lot for the heads up. Couldn't find anything documentation-wise that hinted in that direction.

**Comment by michael-schaefer-eu** [comment] 2020-05-04 08:48
@phil-schreiber  you're welcome. Yes the docs are not complete in this regard, the only hint I could find was here [executing-access-control-rules-after-denormalization](https://api-platform.com/docs/core/security/#executing-access-control-rules-after-denormalization)

**Comment by compri** [comment] 2023-08-07 16:20
This indeed solves the problem for the post collection operation, but what about the get collection operation? Why does the same solution not work with this? 

/**
 * @ApiResource(
 *     iri="https://schema.org/Person",
 *     collectionOperations={
 *          "get" = { "security_post_denormalize" = "is_granted('USER_CREATE', object)" },
 *          "post" = { "security_post_denormalize" = "is_granted('USER_CREATE', object)" }
 *     },
 *     itemOperations={
 *          "get" = { "security" = "is_granted('USER_READ', object)" },
 *          "put" = { "security" = "is_granted('USER_EDIT', object)" },
 *          "delete" = { "security" = "is_granted('USER_DELETE', object)" }
 *     },
 *     shortName="user",
 *  [...]

How can this be solved? Because in the above set up, a user may retrieve any person, without you having any control over that. I think that is almost always a no go in production.
