### ISSUE TITLE
Can properties be restricted based on access control?

### ISSUE THREAD

**Issue by mikemilano** [api-platform/api-platform#789] opened 2018-08-02 05:20 UTC
I would like to know the most idiomatic way to approach restricting properties based on user role, or other access control. I haven't had luck in the docs or slack so far.

For example: On the `User` resource, I'd like the `roles` property to only be accessible to admin users.

The use case would be for building an app where admins can manage other user's roles. Users could also view limited details about each other (their profile), and I'd like to restrict their roles from being exposed here.

Is this possible? and if so, what's the most idiomatic approach?

**Comment by soyuka** [comment] 2018-08-02 07:46
This should do it: https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-dynamically

TLDR: use dynamic groups with a context based on access control

**Comment by teohhanhui** [comment] 2018-08-02 11:35
Duplicate of #773

**Closed by teohhanhui** 2018-08-02 11:35 UTC
Labels: question

**Comment by mikemilano** [comment] 2018-08-02 17:52
That looks like it will do, thanks... closing issue.
