### ISSUE TITLE
cURL error 6: Could not resolve host: varnish

### ISSUE THREAD

**Issue by aanthraxx** [api-platform/api-platform#446] opened 2017-10-30 06:07 UTC
I just recently downloaded the api-platform and tried to study it. When I am trying to to a POST request the data was been successfully saved in the database but the server response I always got was

```json
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "cURL error 6: Could not resolve host: varnish (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/home/jarngotostos/jrn/jrn-api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
      "line": 186,
      "args": []
 

    }
}
```
see https://gist.github.com/Simperfit/eebcfdb72647a982af9e1c8acebe1e08

an INTERNAL SERVER ERROR

**Comment by aanthraxx** [comment] 2017-10-30 06:19
I think I fixed it by removing the value for `varnish_urls` in parameters.yml

**Comment by dunglas** [comment] 2017-10-30 06:50
Were you using the provided Docker setup?

**Comment by meyerbaptiste** [comment] 2017-10-30 11:00
Duplicate of api-platform/core#1389

**Comment by aanthraxx** [comment] 2017-10-30 23:26
@dunglas yes

@meyerbaptiste uhm, the link is not available, i mean the solution

**Comment by meyerbaptiste** [comment] 2017-11-02 09:38
The correct link: https://github.com/api-platform/api-platform/blob/2.1/app/config/config.yml#L85-L92

**Closed** 2018-04-09 14:02 UTC
