### ISSUE TITLE
api-platform.com domain does not resolve

### ISSUE THREAD

**Issue by mrblur** [api-platform/api-platform#2671] opened 2024-03-23 10:55 UTC
...Where do I look for documentation?

**Comment by jay-low** [comment] 2024-03-23 12:08
You can use the docs repository until the problem is fixed: https://github.com/api-platform/docs/

**Comment by dunglas** [comment] 2024-03-24 00:53
My bad. Sorry about that. It's fixed now.

**Closed** 2024-03-24 00:53 UTC
