### ISSUE TITLE
Can not make Entity with name Order

### ISSUE THREAD

**Issue by napestershine** [api-platform/api-platform#1149] opened 2019-05-24 05:37 UTC
HI

I created an entity with name Order. Now when I call to list API. it throws 500 Internal Server Error. Because SQL generated look like this:
`select field1, field2 from order order by desc limit 30`

So it's looking for `by` after first order word. Is there any possibility to have back ticks in auto generated API's CRUD?

Thanks

**Comment by antograssiot** [comment] 2019-05-24 06:19
Closing as duplicate of https://github.com/api-platform/core/issues/2820

**Closed by antograssiot** 2019-05-24 06:19 UTC
