### ISSUE TITLE
Forced to send IRI in embedded entity PUT since version 2.4.7 "No route matches"

### ISSUE THREAD

**Issue by deivid11** [api-platform/api-platform#1287] opened 2019-10-10 19:04 UTC
Hello!
Im using json format for serialization and int identifiers to relate objects, before versión 2.4.7 I was able to update a child object in PUT endpoints like this:

![image](https://user-images.githubusercontent.com/7659305/66598343-77c37300-eb66-11e9-89bf-607157189830.png)

Since versión 2.4.7 version Im getting the error No route matches "1", to avoid the error now I must send an IRI in employee id:

![image](https://user-images.githubusercontent.com/7659305/66598527-d688ec80-eb66-11e9-92f5-de35f95b4cf7.png)

**Comment by teohhanhui** [comment] 2019-10-11 09:09
This looks like a duplicate of https://github.com/api-platform/core/issues/3133. See https://github.com/api-platform/core/pull/3145 for the full explanation.

**Closed by teohhanhui** 2019-10-11 09:09 UTC
