### ISSUE TITLE
[2.2.2] File permission with Docker or dotenv/Flex configuration problem

### ISSUE THREAD

**Issue by piotaixr** [api-platform/api-platform#587] opened 2018-02-25 19:52 UTC
I'm starting a project with api-platform. I want to use Flex and sf4. I saw that v2.2.2 is using these so that's perfect!

I want to a custom user loader with JWT authentication. I also want to use Behat like described in the docs.
I use `docker-compose exec php composer req ...` to add all needed dependencies.

Problem: I now have root-owned files in the project directory.

1) Is it the expected behavior?
2) installing dependencies with the system php installation fails as the dotenv component is missing:
```
[...]
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught RuntimeException: APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file. in /home/piotaixr/dbz/api/sf42/api/bin/console:20
!!  Stack trace:
!!  #0 {main}
!!    thrown in /home/piotaixr/dbz/api/sf42/api/bin/console on line 20
!!  
```

3) The Flex installation also seems broken: the `.env.dist` file is missing so recipes cannot add lines describing the env. vars to add to the configuration

4) At the end, is the release of api-platform compatible for use without docker-compose or without having to use `sudo` or `su` ?

5) It's a disappointment for me that the behat configuration is gone in the new releases

**Comment by dunglas** [comment] 2018-02-25 21:37
Regarding the permission problem, do you use Linux? Maybe can you just "chown" the file on the host after the installation? On Mac there is no problem because Docker handles permissions in a smarter way: https://docs.docker.com/docker-for-mac/osxfs/#ownership
We may need to find a workaround for Linux.

Regarding the env file, Docker has native support for it (https://docs.docker.com/compose/env-file/), it's why we don't install `symfony/dotenv` by default, but if you want to use API Platform on the host directly, you can install it.

Can you give us the step to reproduce the bug with `.env.dist`? Modifying this file should be ignored if it doesn't exist. It looks like a Flex bug to me.

**Comment by Simperfit** [comment] 2018-04-09 10:57
@piotaixr if you still have an issue, please feel free to ping me. Closing as this didn't get anymore feedbacks.

**Closed by Simperfit** 2018-04-09 10:57 UTC

**Comment by teohhanhui** [comment] 2018-04-30 10:02
> Problem: I now have root-owned files in the project directory.

I don't think that's possible to fix other than with user namespace mapping. But it's something that's done at the Docker daemon / host OS level. Personally I don't know enough to make it work lol...

I'd also advise doing `sudo chown $USER: vendor` if it bothers you. It doesn't bother me, unless it's files I need to modify on the host.

> 3. The Flex installation also seems broken: the .env.dist file is missing so recipes cannot add lines describing the env. vars to add to the configuration

That is #643

**Comment by teohhanhui** [comment] 2018-04-30 10:04
> On Mac there is no problem because Docker handles permissions in a smarter way

Actually it's a horrible, horrible way. But it works. Haha...

**Comment by emir** [comment] 2019-04-13 03:23
Same here. I tried to extract with keeping permission from .tar.gz but it didn't work too. Need to give `sudo chown $USER:$USER vendor` inside fresh installed api directory after **docker-compose up**.

**Comment by teohhanhui** [comment] 2019-04-15 20:08
@emir That's normal, as I've mentioned above.
