### ISSUE TITLE
Filter and pagination problem

### ISSUE THREAD

**Issue by abysKri** [api-platform/api-platform#510] opened 2018-01-05 16:05 UTC
hello, can you help me ?

I've a problem with custom api filter.
I tried the example 
- https://api-platform.com/docs/core/filters#creating-custom-filters
and get an error, when i change 'page' parameter:
"hydra:description": "[Semantical Error] line 0, col 48 near 'page = :page_p1': Error: Class APIBundle\\Entity\\Issues has no field or association named page",
My service:
```
services:
    APIBundle\Filter\FindFilter:
        tags: [ 'api_platform.filter' ]
        arguments: [ '@doctrine', '@request_stack', '@?logger', { PublicationStart: ~, Type: ~ } ]
```
My entity annotation
` * @ApiResource(attributes={"filters"={FindFilter::class}})`
```
namespace APIBundle\Filter;

use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\AbstractFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface;
use Doctrine\ORM\QueryBuilder;

final class FindFilter extends AbstractFilter
{
    protected function filterProperty(string $property, $value, QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null)
    {
        $parameterName = $queryNameGenerator->generateParameterName($property);
        $queryBuilder
            ->andWhere(sprintf('o.%s = :%s', $property, $parameterName))
            ->setParameter($parameterName, $value);
    }

    public function getDescription(string $resourceClass): array
    {
        $description = [];
        foreach ($this->properties as $property => $strategy) {
            $description[$property] = [
                'property' => $property,
                'type' => 'string',
                'required' => false,
                'swagger' => [
                    'description' => 'Filter using a regex. This will appear in the Swagger documentation!',
                    'name' => $property,
                    'type' => 'Will appear below the name in the Swagger documentation',
                ],
            ];
        }

        return $description;
    }
}
```

**Comment by jon-ht** [comment] 2018-01-05 16:50
Hi,

Why don't you use AP core pagination ? https://api-platform.com/docs/core/pagination

**Comment by BisKri** [comment] 2018-01-05 21:25
Thanks for the response,
The problem is not pagination, but i get an error when i set page parameter to zero or less than zero.
Api platform seem to have a bug or my "custom filter" test is not good.
what result have you, when yiu set  page = 0 in the swagger ui ?
I work on an test platform and try some poc.

Thanks

**Comment by jon-ht** [comment] 2018-01-05 22:08
When I set page=0 I get "LIMIT argument offset=-30 is not valid" (AP/core v2.1.4). 

Which version do you use ? With v2.1.4 I spotted https://github.com/api-platform/core/blob/v2.1.4/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L89

But this seems to be fixed on master branch https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L106

**Comment by BisKri** [comment] 2018-01-06 00:13
I installed AP with composer install instruction the 2017-12-12.
I'm new, and don't know the exact version:
composer say : 
```

{
    "name": "api-platform/api-platform",
    "license": "MIT",
    "type": "project",
    "description": "The API Platform framework",
    "homepage": "https://api-platform.com",
    "authors": [
        {
            "name": "Kévin Dunglas",
            "email": "dunglas@gmail.com",
            "homepage": "https://dunglas.fr"
        }
    ],
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "autoload-dev": {
        "psr-4": { "Tests\\": "tests/" }
    },
    "require": {
        "php": ">=7.0",
        "api-platform/core": "^2.1",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "guzzlehttp/guzzle": "^6.0",
        "incenteev/composer-parameter-handler": "^2.0",
        "nelmio/cors-bundle": "^1.4",
        "phpdocumentor/reflection-docblock": "^3.0",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0.2",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.3.*",
        "twig/twig": "^1.0 || ^2.0"
    },
    "require-dev": {
        "api-platform/schema-generator": "^2.0",
        "behat/behat": "^3.1",
        "behat/mink": "^1.7",
        "behat/mink-browserkit-driver": "^1.3.1",
        "behat/mink-extension": "^2.2",
        "behat/symfony2-extension": "^2.1",
        "behatch/contexts": "^2.5",
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "hard",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.1-dev"
        }
    }
}

```

**Comment by jon-ht** [comment] 2018-01-07 00:08
I think this is more a bug with your filter.

With these lines

```php
$queryBuilder
        ->andWhere(sprintf('o.%s = :%s', $property, $parameterName))
        ->setParameter($parameterName, $value);
```

you're saying "where issue.page = $value". I'm not sure that's what you want

**Comment by BisKri** [comment] 2018-01-08 15:44
This code come from the doc, https://api-platform.com/docs/core/filters#creating-custom-filters

**Comment by jon-ht** [comment] 2018-01-08 16:11
Maybe I didn't understand your problem. 

What's the purpose of your filter ?

What do you mean by changing page parameter ? Did you change the name or the value passed through SwaggerUI ?

**Comment by BisKri** [comment] 2018-01-10 08:41
Hello,
Same "page=0" parameter problem with a new fresh install.
here is my install log:

```
php composer.phar create-project api-platform/api-platform bookshop-api

Installing api-platform/api-platform (v2.1.4)
  - Installing api-platform/api-platform (v2.1.4): Downloading (100%)
Created project in bookshop-api
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file

Package operations: 67 installs, 0 updates, 0 removals
  - Installing willdurand/negotiation (v2.3.1): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing twig/twig (v2.4.4): Downloading (100%)
  - Installing symfony/polyfill-util (v1.6.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.11): Downloading (100%)
  - Installing symfony/polyfill-php70 (v1.6.0): Downloading (100%)
  - Installing symfony/polyfill-php56 (v1.6.0): Downloading (100%)
  - Installing symfony/symfony (v3.3.13): Downloading (100%)
  - Installing symfony/polyfill-intl-icu (v1.6.0): Downloading (100%)
  - Installing symfony/polyfill-apcu (v1.6.0): Downloading (100%)
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing psr/link (1.0.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing fig/link-util (1.0.0): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/inflector (v1.2.0): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/annotations (v1.5.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing api-platform/core (v2.1.4): Downloading (100%)
  - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
  - Installing doctrine/doctrine-cache-bundle (1.3.2): Downloading (100%)
  - Installing doctrine/dbal (v2.6.3): Loading from cache
  - Installing doctrine/doctrine-bundle (1.8.1): Downloading (100%)
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing doctrine/orm (v2.5.13): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing incenteev/composer-parameter-handler (v2.1.2): Loading from cache
  - Installing nelmio/cors-bundle (1.5.3): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Downloading (100%)
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.3.2): Downloading (100%)
  - Installing composer/ca-bundle (1.0.9): Downloading (100%)
  - Installing sensiolabs/security-checker (v4.1.6): Downloading (100%)
  - Installing sensio/distribution-bundle (v5.0.21): Loading from cache
  - Installing sensio/framework-extra-bundle (v3.0.28): Downloading (100%)
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing symfony/monolog-bundle (v3.1.2): Downloading (100%)
  - Installing swiftmailer/swiftmailer (v5.4.8): Loading from cache
  - Installing symfony/swiftmailer-bundle (v2.6.7): Downloading (100%)
  - Installing league/html-to-markdown (4.6.0): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.6.0): Downloading (100%)
  - Installing php-cs-fixer/diff (v1.2.0): Downloading (100%)
  - Installing gecko-packages/gecko-php-unit (v3.0): Downloading (100%)
  - Installing composer/semver (1.4.2): Downloading (100%)
  - Installing friendsofphp/php-cs-fixer (v2.8.3): Downloading (100%)
  - Installing easyrdf/easyrdf (0.9.1): Loading from cache
  - Installing api-platform/schema-generator (v2.0.2): Downloading (100%)
  - Installing behat/gherkin (v4.5.1): Loading from cache
  - Installing behat/mink (v1.7.1): Loading from cache
  - Installing behat/mink-browserkit-driver (v1.3.2): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing behat/transliterator (v1.2.0): Loading from cache
  - Installing behat/behat (v3.4.3): Downloading (100%)
  - Installing behat/symfony2-extension (2.1.2): Downloading (100%)
  - Installing justinrainbow/json-schema (5.2.6): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing behat/mink-extension (2.3.0): Downloading (100%)
  - Installing behatch/contexts (2.8.0): Downloading (100%)
  - Installing sensio/generator-bundle (v3.1.6): Loading from cache
  - Installing symfony/phpunit-bridge (v3.3.13): Downloading (100%)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/polyfill-intl-icu suggests installing ext-intl (For best performance)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
api-platform/core suggests installing friendsofsymfony/user-bundle (To use the FOSUserBundle bridge.)
doctrine/doctrine-cache-bundle suggests installing symfony/security-acl (For using this bundle to cache ACLs)
sensio/framework-extra-bundle suggests installing symfony/psr-http-message-bridge (To use the PSR-7 converters)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
gecko-packages/gecko-php-unit suggests installing phpunit/phpunit (This is an extension for it so make sure you have it some way.)
easyrdf/easyrdf suggests installing ml/json-ld (~1.0)
behat/mink suggests installing behat/mink-goutte-driver (fast headless driver for any app without JS emulation)
behat/mink suggests installing behat/mink-selenium2-driver (slow, but JS-enabled driver for any app (requires Selenium2))
behat/mink suggests installing behat/mink-zombie-driver (fast and JS-enabled headless driver for any app (requires node.js))
behat/behat suggests installing behat/yii-extension (for integration with Yii web framework)
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Creating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_host (db): localhost
database_port (3306):
database_name (api_platform):
database_user (api_platform): root
database_password (api_platform):
mailer_transport (smtp):
mailer_host (127.0.0.1):
mailer_user (null):
mailer_password (null):
secret (ThisTokenIsNotSoSecretChangeIt): secret
cors_allow_origin ('http://localhost'):
varnish_urls (['http://varnish']):
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug true

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Installing assets as hard copies.

 ---- ------------------- ----------------
       Bundle              Method / Error
 ---- ------------------- ----------------
  OK   ApiPlatformBundle   copy
 ---- ------------------- ----------------

 ! [NOTE] Some assets were installed via copy. If you make changes to these assets you have to run this command again.

 [OK] All assets were successfully installed.

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget

```

**Comment by greg0ire** [comment] 2018-02-25 11:57
@abysKri this file is from the master branch. The master branch is where development happens. It is normal to have a different version. Here is the v2.1.4 version of this file: https://github.com/api-platform/core/blob/v2.1.4/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php

**Closed** 2018-04-09 12:49 UTC
