### ISSUE TITLE
exception_to_status not working with Messenger

### ISSUE THREAD

**Issue by wuestkamp** [api-platform/api-platform#1204] opened 2019-07-25 17:24 UTC
I'm using the Messenger:

```
/**
 * @ApiResource(
 *     messenger=true,
 *     collectionOperations={
 *         "post"={"status"=202}
 *     },
 *     itemOperations={},
 *     output=false
 * )
 */
class MyMessage
{
    /**
     * @var string
     * @Assert\NotNull()
     */
    public $msg;
}
```

and I have a MessageHandler:

```
class MyMessageHandler implements MessageHandlerInterface
{
    public function __invoke(MyMessage $msg)
    {
        throw new Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException();
    }
}
```

I have these settings:

```
api_platform:
    exception_to_status:
        Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: 403
```

But the api still returns error 500?

Is it somehow (also workaround) possible to control the http error code in a message handler? It's working in one of my custom DataProviders.

**Comment by soyuka** [comment] 2019-07-26 11:47
How are you routing your message? It may be an improvement to handle this but indeed I don't think it's supported yet.

**Comment by wuestkamp** [comment] 2019-07-26 12:49
What to you mean by how I route the message? The message/handler doesn't have a specific transport defined, so its execute in sync.

**Comment by soyuka** [comment] 2019-07-26 13:01
That's what I meant thanks. Is the exception thrown? I think we may miss something [here](https://github.com/api-platform/core/blob/9aba73225cbeca44bce34c8250fe0c2494cbfb6f/src/Bridge/Symfony/Messenger/DataPersister.php#L76) to propagate the exception to our ExceptionAction (that handles the exception to status thingy).

**Comment by wuestkamp** [comment] 2019-07-26 13:05
Yes the exception is thrown correctly, so in case of exception I get the status code 500, in case of no exception I get the status code 202 as defined in the `ApiResource` declaration.

**Comment by teohhanhui** [comment] 2019-08-01 12:50
Duplicate of https://github.com/api-platform/core/issues/2856

**Closed by teohhanhui** 2019-08-01 12:50 UTC
