### ISSUE TITLE
[QUESTION] Filter: If the record does not have any results from a mapped join field then don't return those

### ISSUE THREAD

**Issue by worthwhileindustries** [api-platform/api-platform#1039] opened 2019-03-08 03:24 UTC
I have a CatalogRecord, CatalogItem Entity/ApiResource with these joins

```
// CatalogRecord.php
    /**
     * One catalogRecord has many catalogItems. This is the inverse side.
     *
     * @ORM\OneToMany(targetEntity="CatalogItem", mappedBy="catalogRecord")
     * @ORM\JoinColumn(name="catalogID", referencedColumnName="catalogID", unique=true)
     */
    private $catalogItems;
```

```
// CatalogItem.php
    /**
     * Many catalogItems have one catalogRecord. This is the owning side.
     *
     * @ORM\ManyToOne(targetEntity="CatalogRecord", inversedBy="catalogItems")
     * @ORM\JoinColumn(name="catalogID", referencedColumnName="catalogID")
     */
    private $catalogRecord;
```

I created a filter like
```
        $queryBuilder->addSelect('COUNT(' . $associationAlias . '.id) as itemCount');
        $queryBuilder->addGroupBy($alias . '.id');
        $queryBuilder->having('itemCount > 0');
```

I get this error
```
An exception occurred while executing 'SELECT DISTINCT catalogID_0 FROM (SELECT DISTINCT catalogID_0 FROM (SELECT c0_.catalogID AS catalogID_0, COUNT(i1_.itemID) AS sclr_1, i1_.itemID AS itemID_2 FROM catalog c0_ LEFT JOIN item i1_ ON c0_.catalogID = i1_.catalogID GROUP BY c0_.catalogID HAVING sclr_1 > 0) dctrn_result_inner ORDER BY catalogID_0 ASC) dctrn_result LIMIT 25':\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'rise.i1_.itemID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

If I add groupby on this `'rise.i1_.itemID'` then I get duplicate results and an error below so, I'm not sure where to go from here. Is there an easier way to do this? Any help would be much appreciated.

```
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "The JSON API document must contain a \"data\" key.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/srv/api/vendor/api-platform/core/src/JsonApi/Serializer/CollectionNormalizer.php",
      "line": 87,
      "args": []
    },
    {
      "namespace": "ApiPlatform\\Core\\JsonApi\\Serializer",
      "short_class": "CollectionNormalizer",
      "class": "ApiPlatform\\Core\\JsonApi\\Serializer\\CollectionNormalizer",
      "type": "->",
      "function": "getItemsData",
      "file": "/srv/api/vendor/api-platform/core/src/Serializer/AbstractCollectionNormalizer.php",
      "line": 93,
      "args": [
        [
          "object",
          "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Paginator"
        ],
        [
          "string",
          "jsonapi"
        ],
        [
          "array",
          {
            "collection_operation_name": [
              "string",
              "get"
            ],
            "operation_type": [
              "string",
              "collection"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "input_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "output_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "request_uri": [
              "string",
              "/api/catalog-record?hasCatalogItems=true"
            ],
            "uri": [
              "string",
              "https://localhost:8443/api/catalog-record?hasCatalogItems=true"
            ],
            "resources": [
              "object",
              "ApiPlatform\\Core\\Serializer\\ResourceList"
            ],
            "resources_to_push": [
              "object",
              "ApiPlatform\\Core\\Serializer\\ResourceList"
            ],
            "api_sub_level": [
              "boolean",
              true
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\Serializer",
      "short_class": "AbstractCollectionNormalizer",
      "class": "ApiPlatform\\Core\\Serializer\\AbstractCollectionNormalizer",
      "type": "->",
      "function": "normalize",
      "file": "/srv/api/vendor/symfony/serializer/Serializer.php",
      "line": 152,
      "args": [
        [
          "object",
          "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Paginator"
        ],
        [
          "string",
          "jsonapi"
        ],
        [
          "array",
          {
            "collection_operation_name": [
              "string",
              "get"
            ],
            "operation_type": [
              "string",
              "collection"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "input_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "output_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "request_uri": [
              "string",
              "/api/catalog-record?hasCatalogItems=true"
            ],
            "uri": [
              "string",
              "https://localhost:8443/api/catalog-record?hasCatalogItems=true"
            ],
            "resources": [
              "object",
              "ApiPlatform\\Core\\Serializer\\ResourceList"
            ],
            "resources_to_push": [
              "object",
              "ApiPlatform\\Core\\Serializer\\ResourceList"
            ],
            "api_sub_level": [
              "boolean",
              true
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer",
      "short_class": "Serializer",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "function": "normalize",
      "file": "/srv/api/vendor/symfony/serializer/Serializer.php",
      "line": 125,
      "args": [
        [
          "object",
          "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Paginator"
        ],
        [
          "string",
          "jsonapi"
        ],
        [
          "array",
          {
            "collection_operation_name": [
              "string",
              "get"
            ],
            "operation_type": [
              "string",
              "collection"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "input_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "output_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "request_uri": [
              "string",
              "/api/catalog-record?hasCatalogItems=true"
            ],
            "uri": [
              "string",
              "https://localhost:8443/api/catalog-record?hasCatalogItems=true"
            ],
            "resources": [
              "object",
              "ApiPlatform\\Core\\Serializer\\ResourceList"
            ],
            "resources_to_push": [
              "object",
              "ApiPlatform\\Core\\Serializer\\ResourceList"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer",
      "short_class": "Serializer",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "function": "serialize",
      "file": "/srv/api/vendor/api-platform/core/src/EventListener/SerializeListener.php",
      "line": 87,
      "args": [
        [
          "object",
          "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\Paginator"
        ],
        [
          "string",
          "jsonapi"
        ],
        [
          "array",
          {
            "collection_operation_name": [
              "string",
              "get"
            ],
            "operation_type": [
              "string",
              "collection"
            ],
            "resource_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "input_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "output_class": [
              "string",
              "App\\Entity\\CatalogRecord"
            ],
            "request_uri": [
              "string",
              "/api/catalog-record?hasCatalogItems=true"
            ],
            "uri": [
              "string",
              "https://localhost:8443/api/catalog-record?hasCatalogItems=true"
            ],
            "resources": [
              "object",
              "ApiPlatform\\Core\\Serializer\\ResourceList"
            ],
            "resources_to_push": [
              "object",
              "ApiPlatform\\Core\\Serializer\\ResourceList"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\EventListener",
      "short_class": "SerializeListener",
      "class": "ApiPlatform\\Core\\EventListener\\SerializeListener",
      "type": "->",
      "function": "onKernelView",
      "file": "/srv/api/vendor/symfony/event-dispatcher/Debug/WrappedListener.php",
      "line": 111,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ],
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "WrappedListener",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
      "type": "->",
      "function": "__invoke",
      "file": "/srv/api/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 212,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ],
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\EventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "doDispatch",
      "file": "/srv/api/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 44,
      "args": [
        [
          "array",
          [
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ]
          ]
        ],
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/api/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php",
      "line": 145,
      "args": [
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "TraceableEventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/api/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 155,
      "args": [
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handleRaw",
      "file": "/srv/api/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 67,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/api/vendor/symfony/http-kernel/Kernel.php",
      "line": 198,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ],
        [
          "boolean",
          true
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "Kernel",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/api/public/index.php",
      "line": 42,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ]
      ]
    }
  ]
}
```

**Comment by teohhanhui** [comment] 2019-03-08 16:53
Duplicate of https://github.com/api-platform/core/issues/2154

The short answer is: No.

If we are going to add such a feature, we'll have to figure out how to convey the correct semantics. (How do you tell when a relation contains only matching items?)

**Comment by worthwhileindustries** [comment] 2019-03-09 02:43
@teohhanhui I can't do the reverse with this method but, I think this is a workaround for the desired results. I only get CatalogRecords that have matching CatalogItems. I made a new filter with...
```
$associationAlias = QueryBuilderHelper::addJoinOnce($queryBuilder, $queryNameGenerator, $alias, $association, Join::INNER_JOIN);
```

I have limited experience with the platform. If I think of something I'll be happy to reply back. Thanks

**Closed** 2019-03-26 13:44 UTC
