### ISSUE TITLE
Serialization of 'Closure' is not allowed in ApiSubresource

### ISSUE THREAD

**Issue by leandro980** [api-platform/api-platform#1789] opened 2021-02-02 15:44 UTC
**API Platform version(s) affected**: 2.6.1

**Description**  
Using ApiSubresource falls to an internal server error caused by `Serialization of 'Closure' is not allowed`

**How to reproduce**  
I got a User Entity with
```php
/**
     * @var Collection|UserCustomerAssociation[]
     * @ORM\OneToMany(targetEntity=UserCustomerAssociation::class, mappedBy="user", orphanRemoval=true)
     * @Groups({"user:read"})
     * @ApiSubresource
     */
    private Collection|array $userCustomerAssociations;

    public function __construct()
    {
        $this->userCustomerAssociations = new ArrayCollection();
    }
```

and a UserCustomerAssociation
```php
namespace App\Entity\Security;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Entity\Data\Customer;
use App\Repository\Security\UserCustomerAssociationRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\UuidInterface;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource( normalizationContext={"groups"={"user-customer:read"}},
 *              denormalizationContext={"groups"={"user-customer:write"}})
 * @ORM\Table(name="security_utente_cliente",
 *     uniqueConstraints={@ORM\UniqueConstraint(name="unique_association", columns={"utente_id", "cliente_id"})})
 * @ORM\Entity(repositoryClass=UserCustomerAssociationRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class UserCustomerAssociation
{

    public const METHOD_PHONE = 'p',
                 METHOD_EMAIL = 'e',
                 METHOD_ADMIN = 'a';

    public array $verificationMethodDescription = [
        self::METHOD_ADMIN => 'Admin',
        self::METHOD_EMAIL => 'Email',
        self::METHOD_PHONE => 'Telefono',
    ];

    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @Groups({"user-customer:read"})
     */
    private ?UuidInterface $id = null;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="userCustomerAssociations")
     * @ORM\JoinColumn(name="utente_id", nullable=false, onDelete="CASCADE")
     * @Groups({"user-customer:read", "user-customer:write"})
     */
    private ?User $user;

    /**
     * @ORM\ManyToOne(targetEntity=Customer::class)
     * @ORM\JoinColumn(name="cliente_id", nullable=false, onDelete="CASCADE")
     * @Groups({"user-customer:read", "user-customer:write",
     *     "user:read"})
     */
    private ?Customer $customer;
```
Calling the subresource endpoint gives the correct answer and an error... This is an error that i have for all subresources

```json
{
    "@context": "/api/contexts/UserCustomerAssociation",
    "@id": "/api/users/0687c906-209a-4d27-b0ce-2539447331fa/user_customer_associations",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/api/user_customer_associations/0687c906-209a-4d27-b0ce-2539447331fa",
            "@type": "UserCustomerAssociation",
            "id": "0687c906-209a-4d27-b0ce-2539447331fa",
            "user": "/api/users/0687c906-209a-4d27-b0ce-2539447331fa",
            "customer": "/api/customers/404406",
            "verificationMethod": "a",
            "isVerified": true
        }
    ],
    "hydra:totalItems": 1
}{
    "@context": "/api/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Serialization of 'Closure' is not allowed",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/path/to/project/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php",
            "line": 175,
            "args": []
        },
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "serialize",
            "file": "/path/to/project/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php",
            "line": 175,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\HttpKernel\\Profiler",
            "short_class": "FileProfilerStorage",
            "class": "Symfony\\Component\\HttpKernel\\Profiler\\FileProfilerStorage",
            "type": "->",
            "function": "write",
            "file": "/path/to/project/vendor/symfony/http-kernel/Profiler/Profiler.php",
            "line": 101,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\HttpKernel\\Profiler",
            "short_class": "Profiler",
            "class": "Symfony\\Component\\HttpKernel\\Profiler\\Profiler",
            "type": "->",
            "function": "saveProfile",
            "file": "/path/to/project/vendor/symfony/http-kernel/EventListener/ProfilerListener.php",
            "line": 112,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\HttpKernel\\EventListener",
            "short_class": "ProfilerListener",
            "class": "Symfony\\Component\\HttpKernel\\EventListener\\ProfilerListener",
            "type": "->",
            "function": "onKernelTerminate",
            "file": "/path/to/project/vendor/symfony/event-dispatcher/Debug/WrappedListener.php",
            "line": 117,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
            "short_class": "WrappedListener",
            "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
            "type": "->",
            "function": "__invoke",
            "file": "/path/to/project/vendor/symfony/event-dispatcher/EventDispatcher.php",
            "line": 230,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\EventDispatcher",
            "short_class": "EventDispatcher",
            "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
            "type": "->",
            "function": "callListeners",
            "file": "/path/to/project/vendor/symfony/event-dispatcher/EventDispatcher.php",
            "line": 59,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\EventDispatcher",
            "short_class": "EventDispatcher",
            "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
            "type": "->",
            "function": "dispatch",
            "file": "/path/to/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php",
            "line": 151,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
            "short_class": "TraceableEventDispatcher",
            "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
            "type": "->",
            "function": "dispatch",
            "file": "/path/to/project/vendor/symfony/http-kernel/HttpKernel.php",
            "line": 99,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\HttpKernel",
            "short_class": "HttpKernel",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "type": "->",
            "function": "terminate",
            "file": "/path/to/project/vendor/symfony/http-kernel/Kernel.php",
            "line": 152,
            "args": []
        },
        {
            "namespace": "Symfony\\Component\\HttpKernel",
            "short_class": "Kernel",
            "class": "Symfony\\Component\\HttpKernel\\Kernel",
            "type": "->",
            "function": "terminate",
            "file": "/path/to/project/public/index.php",
            "line": 30,
            "args": []
        }
    ]
}
```

**Comment by soyuka** [comment] 2021-02-02 15:49
duplicate of https://github.com/api-platform/core/issues/3976 thanks for the detailed report! Disabling the profiler helps we're currently investigating!

**Closed by soyuka** 2021-02-02 15:49 UTC
