### ISSUE TITLE
Xdebug integration

### ISSUE THREAD

**Issue by Larzack** [api-platform/api-platform#796] opened 2018-08-05 08:51 UTC
@teohhanhui,

Is it possible to integrate Xdebug for development ?
We will be able to debug through the docker image
It was a little hard for me to integrate it because I'm on MAC and the network integration is a bit different from a classic Linux integration.

I made it for MAC, which has only 1 or 2 extra lines than Linux. It should work for Windows too.

If I add it to the project ( should I add it to api-platform or demo ? )

Regards

**Comment by borNfreee** [comment] 2018-08-05 08:53
Could you please explain it here at least (if it won't go to the official code/documentation)?

**Comment by teohhanhui** [comment] 2018-08-07 12:38
@Larzack We could add a docs entry for this. Duplicate of #782 and api-platform/docs#511

**Closed by teohhanhui** 2018-08-07 12:38 UTC
