### ISSUE TITLE
Filter not working with embedded properties (multiple levels)

### ISSUE THREAD

**Issue by blaues0cke** [api-platform/api-platform#297] opened 2017-05-09 12:34 UTC
I dont know if this relates to https://github.com/api-platform/api-platform/issues/277 but I have a issue with filtering by embedded properties. For example, I have to following entity structure:

* `User` has `Profile`
* `Profile` has `Address`
* `Address` has `postalCode` (`string`)

So when I call

`/api/users?profile.address.postalCode=88`

with the filter configuration

```
filter.search_user:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { profile.firstName: 'partial', profile.lastName: 'partial', profile.address.postalCode: 'starts' } ]
        tags:      [ { name: 'api_platform.filter', id: 'filter.search_user' } ]
```

I would expect a response that only contains users with a postal code starting with `88`. But all users are returned since the filter is not applied at all.

The same issue occurs when I call

`/api/users?profile.firstName=Thomas`

what should return only users with `Thomas` in their `firstName` but all users are returned. I digged a lot in the issues and found https://github.com/api-platform/core/pull/242 and https://github.com/api-platform/core/issues/83.

So is this already a feature and/or am I facing a bug?

**EDIT**: Thought that only occurs with embedded entities deeper that one level. But it seems its not possible to filter by embedded entity properties at all.

**Comment by soyuka** [comment] 2017-05-09 12:43
Do the filters show up in the hydra metadata? We've a test on this and AFAIR it's working to me.

**Comment by blaues0cke** [comment] 2017-05-09 12:56
@soyuka You are right, all embedded filter do **not** appear in the metadata. Its seems that all embedded relations are skipped. I tested this with another entity in my project that is called `Scan`. This property has also an embedded `Address` but also a property called `title`. The following filter definition seems to work, expect that the embedded property is skipped at all.

```
filter.search_scan:
    parent:    'api_platform.doctrine.orm.search_filter'
    arguments: [ { store.title: 'partial', status: 'exact', store.address.postalCode: 'starts' } ]
    tags:      [ { name: 'api_platform.filter', id: 'filter.search_scan' } ]
```

The response lists `store.title` in `hydra:search`, but not `store.address.postalCode`:

```
"hydra:search": {
    "@type": "hydra:IriTemplate",
    "hydra:template": "/app_dev.php/api/scans{?creationDate[before],creationDate[after],order[creationDate],store.title,status,status[],geoOnly}",
    "hydra:variableRepresentation": "BasicRepresentation",
    "hydra:mapping": [
      {
        "@type": "IriTemplateMapping",
        "variable": "creationDate[before]",
        "property": "creationDate",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "creationDate[after]",
        "property": "creationDate",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "order[creationDate]",
        "property": "creationDate",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "store.title",
        "property": "store.title",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "status",
        "property": "status",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "status[]",
        "property": "status",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "geoOnly",
        "property": "geoOnly",
        "required": false
      }
    ]
  }
```

**Comment by Simperfit** [comment] 2017-05-09 12:59
This is not working `/api/users?profile.address.postalCode=88` because this is 2 level.
`/api/users?profile.firstName=Thomas` this should be working, could you please show us the hydra return ?

**Comment by soyuka** [comment] 2017-05-09 13:14
@Simperfit should work with as many levels as we need:

![filters](https://cloud.githubusercontent.com/assets/1321971/25852518/ec5e9b8c-34c9-11e7-8e95-180f5391c74d.png)

Extract of filters services:

```yaml
    product_referencing.filter.date:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { 'fromDate': 'include_null_after', 'thruDate': 'include_null_after' } ]
        tags: [ {name: 'api_platform.filter', id: 'product_referencing.filter.date' }]

    product_referencing.filter.enabled:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { 'enabled': ~, 'product.productToPackaging.isDefault': ~, 'product.productInternalOrganization.referencingStatus.isBlocking': ~} ]
        tags: [ {name: 'api_platform.filter', id: 'product_referencing.filter.enabled' }]

    product_referencing.filter.product:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { 'product': 'exact', 'product.category.id': 'exact', 'product.priceDefinitionFamily.id': 'exact', 'product.code': 'exact', 'product.productInternalOrganization.internalOrganization': 'exact' } ]
        tags: [ {name: 'api_platform.filter', id: 'product_referencing.filter.product' }]
```

**Comment by blaues0cke** [comment] 2017-05-09 15:23
Thanks. I cannot find any differences between the example from @soyuka and my code. Also I can remember that at least the filter on embedded entities on the first level worked. Maybe the update from `2.0.3` to `2.0.7` changed something under the hood? Will dig into this tomorrow. Any hints where I should start debugging?

**Comment by soyuka** [comment] 2017-05-09 15:51
Note that I'm on master, helps me testing new features :p.

For debugging:

1. `bin/console debug:container` - check that your filters are okay there
2. You can check [here](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/FilterExtension.php#L52) if anything looks suspicious / confirm that filters are being used
3. Check [here](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php#L168) if some condition is the trouble you may find a direct answer

**Comment by soyuka** [comment] 2017-05-10 14:22
@blaues0cke could you give me your resource declaration?

Filters declared on collection operations will take precedence over global resource attributes filters declarations. Both values are not merged, could be your issue.
Also, make sure that you have no cache or that you clear it.

**Comment by blaues0cke** [comment] 2017-05-11 11:05
@soyuka Are you sure that this relates to my issue? Since `store.title` and `status` are present, but `store.address.postalCode` not, but they are defined in the same filter definition.

```
filter.search_scan:
    parent:    'api_platform.doctrine.orm.search_filter'
    arguments: [ { store.title: 'partial', status: 'exact', store.address.postalCode: 'starts' } ]
    tags:      [ { name: 'api_platform.filter', id: 'filter.search_scan' } ]
```

**Comment by soyuka** [comment] 2017-05-12 07:47
I mean the `resource` declaration, not the filter service declaration.

**Comment by blaues0cke** [comment] 2017-05-12 08:21
@soyuka For sure, here you go (I removed unnecessary properties):

`Entity\Scan.php`:

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource(
 *     attributes={
 *         "denormalization_context"={
 *             "groups"={
 *                 "scan_write"
 *             }
 *         },
 *         "filters"={
 *             "filter.date_scan",
 *             "filter.order_scan",
 *             "filter.search_scan",
 *             "filter.geoOnly"
 *         },
 *         "normalization_context"={
 *             "groups"={
 *                 "scan_read"
 *             }
 *         }
 *     },
 *     itemOperations={
 *         "get"={
 *             "method"="GET"
 *         }
 *     }
 * )
 *
 * @ORM\Entity()
 * @ORM\Table()
 */
class Scan
{
    /**
     * @var string The id of this scan.
     *
     * @ORM\Column(type="guid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    protected $id;

    /**
     * @var Store The store in that this scan was created.
     *
     * @ORM\ManyToOne(targetEntity="Store", inversedBy="scans")
     *
     * @Groups({
     *     "campaign_participation_app_admin_read",
     *     "scan_app_admin_read",
     *     "scan_self_read",
     *     "scan_write"
     * })
     */
    protected $store;

    /**
     * The status of this scan (e.g. "open")
     *
     * @var string Status
     *
     * @ORM\Column
     *
     * @Groups({
     *     "campaign_participation_app_admin_read",
     *     "scan_app_admin_read",
     *     "scan_self_read",
     *     "store_app_admin_read"
     * })
     */
    protected $status;
```

`Entity\Store.php`:

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Ldap\Adapter\ExtLdap\Adapter;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource(
 *     attributes={
 *         "denormalization_context"={
 *             "groups"={
 *
 *             }
 *         },
 *         "filters"={
 *             "filter.order_store",
 *             "filter.search_store",
 *             "filter.range_store"
 *         },
 *         "normalization_context"={
 *             "groups"={
 *                 "store_read"
 *             }
 *         }
 *     },
 *     collectionOperations={
 *         "get"={
 *             "method"="GET"
 *         }
 *     },
 *     itemOperations={
 *         "get"={
 *             "method"="GET"
 *         }
 *     }
 * )
 *
 * @ORM\Entity()
 * @ORM\Table()
 */
class Store
{
    /**
     * @var Address Address assigned to this store.
     *
     * @ORM\Embedded(class="Address")
     *
     * @Groups({
     *     "scan_app_admin_read",
     *     "scan_read",
     *     "store_read"
     * })
     */
    protected $address;

    /**
     * @var string The id of this store.
     *
     * @ORM\Column(type="guid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    protected $id;

    /**
     * @var string The title of this store (e.g. "EDEKA").
     *
     * @Assert\NotBlank
     * @ORM\Column
     *
     * @Groups({
     *     "scan_app_admin_read",
     *     "scan_read",
     *     "store_read"
     * })
     */
    protected $title;
}
```

`Entity\Address.php`:

```
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Embeddable
 */
class Address
{
    /**
     * @var string The postal code part of this address.
     *
     * @ORM\Column(nullable=true)
     *
     * @Groups({
     *     "account_balance_change_app_admin_read",
     *     "app_read",
     *     "campaign_participation_app_admin_read",
     *     "payout_request_app_admin_read",
     *     "scan_app_admin_read",
     *     "scan_read",
     *     "store_read",
     *     "user_app_admin_read",
     *     "user_self_read",
     *     "user_self_write"
     * })
     */
    protected $postalCode;
}
```

Also, I am in slack for the next few hours and on to figure out this issue, too.

**Comment by teohhanhui** [comment] 2017-05-12 08:39
This is a duplicate of api-platform/core#969

There is an open PR at api-platform/core#984

**Closed by teohhanhui** 2017-05-12 08:39 UTC

**Comment by blaues0cke** [comment] 2017-05-15 13:21
Thanks. Can confirm that https://github.com/api-platform/core/pull/984 works like a charm. Also I accidentally used `starts` instead of `start`.
