### ISSUE TITLE
generate-api-platform-client raises an Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by sushicodeur** [api-platform/api-platform#1074] opened 2019-03-28 15:12 UTC
We always developed custom client but this time I decided to give the client generator a go, especially to see how mercure is supposed to work.

When I run 

```sh
docker-compose exec client generate-api-platform-client
```

I get the following error 

```
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@api-platform/api-doc-parser/lib/swagger/handleJson.js:48:15)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

I'm using an almost fresh install of 2.4.1 distribution of Api-Platform, what I'm missing ?

**Comment by dunglas** [comment] 2019-03-29 07:22
Duplicate of https://github.com/api-platform/client-generator/issues/108

**Closed by dunglas** 2019-03-29 07:23 UTC
